/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CcChat {
        "chatbotId": string;
    }
    interface CcChatBubble {
        "fill": string;
    }
    interface CcChevronDown {
        "stroke": string;
    }
    interface CcHints {
        "messages": string[];
    }
    interface CcToggle {
        "bgColor": string;
        "fgColor": string;
    }
    interface CcXMark {
        "fill": string;
        "size": string;
    }
    interface CreateChatbot {
        "chatbotId": string;
    }
}
declare global {
    interface HTMLCcChatElement extends Components.CcChat, HTMLStencilElement {
    }
    var HTMLCcChatElement: {
        prototype: HTMLCcChatElement;
        new (): HTMLCcChatElement;
    };
    interface HTMLCcChatBubbleElement extends Components.CcChatBubble, HTMLStencilElement {
    }
    var HTMLCcChatBubbleElement: {
        prototype: HTMLCcChatBubbleElement;
        new (): HTMLCcChatBubbleElement;
    };
    interface HTMLCcChevronDownElement extends Components.CcChevronDown, HTMLStencilElement {
    }
    var HTMLCcChevronDownElement: {
        prototype: HTMLCcChevronDownElement;
        new (): HTMLCcChevronDownElement;
    };
    interface HTMLCcHintsElement extends Components.CcHints, HTMLStencilElement {
    }
    var HTMLCcHintsElement: {
        prototype: HTMLCcHintsElement;
        new (): HTMLCcHintsElement;
    };
    interface HTMLCcToggleElement extends Components.CcToggle, HTMLStencilElement {
    }
    var HTMLCcToggleElement: {
        prototype: HTMLCcToggleElement;
        new (): HTMLCcToggleElement;
    };
    interface HTMLCcXMarkElement extends Components.CcXMark, HTMLStencilElement {
    }
    var HTMLCcXMarkElement: {
        prototype: HTMLCcXMarkElement;
        new (): HTMLCcXMarkElement;
    };
    interface HTMLCreateChatbotElement extends Components.CreateChatbot, HTMLStencilElement {
    }
    var HTMLCreateChatbotElement: {
        prototype: HTMLCreateChatbotElement;
        new (): HTMLCreateChatbotElement;
    };
    interface HTMLElementTagNameMap {
        "cc-chat": HTMLCcChatElement;
        "cc-chat-bubble": HTMLCcChatBubbleElement;
        "cc-chevron-down": HTMLCcChevronDownElement;
        "cc-hints": HTMLCcHintsElement;
        "cc-toggle": HTMLCcToggleElement;
        "cc-x-mark": HTMLCcXMarkElement;
        "create-chatbot": HTMLCreateChatbotElement;
    }
}
declare namespace LocalJSX {
    interface CcChat {
        "chatbotId"?: string;
    }
    interface CcChatBubble {
        "fill"?: string;
    }
    interface CcChevronDown {
        "stroke"?: string;
    }
    interface CcHints {
        "messages"?: string[];
    }
    interface CcToggle {
        "bgColor"?: string;
        "fgColor"?: string;
    }
    interface CcXMark {
        "fill"?: string;
        "size"?: string;
    }
    interface CreateChatbot {
        "chatbotId"?: string;
    }
    interface IntrinsicElements {
        "cc-chat": CcChat;
        "cc-chat-bubble": CcChatBubble;
        "cc-chevron-down": CcChevronDown;
        "cc-hints": CcHints;
        "cc-toggle": CcToggle;
        "cc-x-mark": CcXMark;
        "create-chatbot": CreateChatbot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cc-chat": LocalJSX.CcChat & JSXBase.HTMLAttributes<HTMLCcChatElement>;
            "cc-chat-bubble": LocalJSX.CcChatBubble & JSXBase.HTMLAttributes<HTMLCcChatBubbleElement>;
            "cc-chevron-down": LocalJSX.CcChevronDown & JSXBase.HTMLAttributes<HTMLCcChevronDownElement>;
            "cc-hints": LocalJSX.CcHints & JSXBase.HTMLAttributes<HTMLCcHintsElement>;
            "cc-toggle": LocalJSX.CcToggle & JSXBase.HTMLAttributes<HTMLCcToggleElement>;
            "cc-x-mark": LocalJSX.CcXMark & JSXBase.HTMLAttributes<HTMLCcXMarkElement>;
            "create-chatbot": LocalJSX.CreateChatbot & JSXBase.HTMLAttributes<HTMLCreateChatbotElement>;
        }
    }
}
