/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatbotWrapper {
        "chatbotId": string;
    }
}
declare global {
    interface HTMLChatbotWrapperElement extends Components.ChatbotWrapper, HTMLStencilElement {
    }
    var HTMLChatbotWrapperElement: {
        prototype: HTMLChatbotWrapperElement;
        new (): HTMLChatbotWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "chatbot-wrapper": HTMLChatbotWrapperElement;
    }
}
declare namespace LocalJSX {
    interface ChatbotWrapper {
        "chatbotId"?: string;
    }
    interface IntrinsicElements {
        "chatbot-wrapper": ChatbotWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chatbot-wrapper": LocalJSX.ChatbotWrapper & JSXBase.HTMLAttributes<HTMLChatbotWrapperElement>;
        }
    }
}
