/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Chatbot } from "./models/chatbot";
export { Chatbot } from "./models/chatbot";
export namespace Components {
    interface ChatBubble {
        "fill": string;
    }
    interface ChatbotWrapper {
        "chatbotId": string;
    }
    interface ToggleButton {
        "chatbot": Chatbot;
    }
}
declare global {
    interface HTMLChatBubbleElement extends Components.ChatBubble, HTMLStencilElement {
    }
    var HTMLChatBubbleElement: {
        prototype: HTMLChatBubbleElement;
        new (): HTMLChatBubbleElement;
    };
    interface HTMLChatbotWrapperElement extends Components.ChatbotWrapper, HTMLStencilElement {
    }
    var HTMLChatbotWrapperElement: {
        prototype: HTMLChatbotWrapperElement;
        new (): HTMLChatbotWrapperElement;
    };
    interface HTMLToggleButtonElement extends Components.ToggleButton, HTMLStencilElement {
    }
    var HTMLToggleButtonElement: {
        prototype: HTMLToggleButtonElement;
        new (): HTMLToggleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "chat-bubble": HTMLChatBubbleElement;
        "chatbot-wrapper": HTMLChatbotWrapperElement;
        "toggle-button": HTMLToggleButtonElement;
    }
}
declare namespace LocalJSX {
    interface ChatBubble {
        "fill"?: string;
    }
    interface ChatbotWrapper {
        "chatbotId"?: string;
    }
    interface ToggleButton {
        "chatbot"?: Chatbot;
    }
    interface IntrinsicElements {
        "chat-bubble": ChatBubble;
        "chatbot-wrapper": ChatbotWrapper;
        "toggle-button": ToggleButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-bubble": LocalJSX.ChatBubble & JSXBase.HTMLAttributes<HTMLChatBubbleElement>;
            "chatbot-wrapper": LocalJSX.ChatbotWrapper & JSXBase.HTMLAttributes<HTMLChatbotWrapperElement>;
            "toggle-button": LocalJSX.ToggleButton & JSXBase.HTMLAttributes<HTMLToggleButtonElement>;
        }
    }
}
